# Rede A (Sub-rede 192.168.20.0/24)
pc0[0]=A
pc1[0]=A
r2[0]=A

# Rede B (Sub-rede 192.168.30.0/24)
pc2[0]=B
pc3[0]=B
r3[0]=B

# Rede C (Backbone / Sub-rede 192.168.10.0/24)
r1[0]=C
r2[1]=C
r3[1]=C
dhcpserver[0]=C

# Rede D (Internet / Link de Saída)
r1[1]=D
internet[0]=D
